name: Ruby Gem

on: workflow_dispatch

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Get Gem Version
      id: get-version
      run: |
        VERSION=$(ruby -r './lib/facera/version.rb' -e "puts Facera::VERSION")
        echo "::set-output name=version::$VERSION"
      shell: bash

    - name: Publish to RubyGems
      run: |
        gem fetch facera -v ${{ steps.get-version.outputs.version }}
        if [ $? -eq 1 ]; then
          echo "Gem version already exists on RubyGems. Skipping the push to RubyGems."
          exit 0
        fi
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      shell: bash
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
